//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public int TripId { get; set; }
        public System.DateTime TripDate { get; set; }
        public int AirportId { get; set; }
        public int TransTypeId { get; set; }
        public string GroupName { get; set; }
        public int GroupSize { get; set; }
    
        public virtual Airport Airport { get; set; }
        public virtual TransType TransType { get; set; }
    }
}
